### ISSUE TITLE
[GTK3] Can't resize Size column in detailed view

### ISSUE THREAD

**Issue by kamiyaa** [IgnorantGuru/spacefm#612]
The "size" option in detailed view can't be resize to take up less/more space.
The scrollbar seems to be covering it.; every time the mouse hovers there, the scrollbar appears and prevents me from changing the size.
I think this might be caused by the new gtk3.
I am running gtk-3.16.7 on Gentoo Linux.

**Comment by IgnorantGuru** [comment]
Have you tested this using the default GNOME/GTK3 theme 'Adwaita'?  This sounds like a likely broken theme.  Note that in GTK3, themes often break when new minor versions of GTK are released.  If using a 3rd party theme, you may need to contact the theme developer or download a version of the theme consistent with your latest GTK3 version.

The vertical scrollbar should always be visible, it does not hide.  The horizontal scrollbar only appears when needed, at the bottom of the list.  Its visibility should not change based on mouse hover.  In no case should they cover the column headers or dragable dividers.

**Comment by ShanaXXII** [comment]
I don't have the adwaita theme installed, but I have the raleigh theme which was the default theme that it came with. I tried that and the scrollbars are still disappearing/reappearing.
I remembered this not behaviour not happening before with the raleigh theme.
http://s15.postimg.org/ufc1bdtq3/spacefm.png

**Comment by OmegaPhil** [comment]
Have just tested in GTK3 with the Xfce-basic theme (GTK 3.18.6) - I can move the size column to the end, and resize it (although resizing from the right side is a bit fiddly due to the scrollbar).

**Comment by IgnorantGuru** [comment]
> I don't have the adwaita theme installed, but I have the raleigh theme which was the default theme that it came with.

Raleigh is the default GTK2 theme.  In GTK3, the default is Adwaita, and Adwaita should be used as a control to determine if it is a theme-related problem.  If you are using a "Raleigh" on GTK3, it is likely a 3rd party theme, even if Gentoo is using it by default.  So this problem is likely due to a change in GTK3 which broke the 3rd party Raleigh theme you're using.  It will probably have to be corrected by fixing that theme.  It should probably be reported as a GTK theme bug.

Closing this as it's not reproduced with Adwaita, but feel free to add more info or details.

As a workaround, you can probably add another column after Size (or drag one there), then resize the Size column while it's not along the right side, then remove the column you added.  To add a column, see View|Panel n View|Columns menu.

**Comment by IgnorantGuru** [comment]
Another possibility to note here would be if the newer version of GTK3 has an option to auto-hide the scrollbar except on hover, which is overriding the explicit setting of 'always-show' which SpaceFM uses for that vertical scrollbar.

However, even if that is the case, any problem with dragging the column divider to resize it would indicate an internal GTK bug or a theme bug, because SpaceFM does not handle the resizing directly.  That is done via a built-in GTK handler.

**Comment by IgnorantGuru** [comment]
And your screenshot looks more like GTK2 than 3, but that could be the theme.  To see which version SpaceFM is really using, run:

    spacefm --version

In your screenshots, the first two are impossible (incorrect).

**Comment by ShanaXXII** [comment]
$ spacefm --version
    spacefm 1.0.4
    GTK3 UDEV INOTIFY DESKTOP
Thanks for the advice of moving it over to the left and resizing it.
I installed and changed my theme to Adwaita and the same problem persists.
I have gtk-3.16.7 and adwaita 3.16.2 on dwm.

**Comment by IgnorantGuru** [comment]
Since you're seeing this with Adwaita, it could indicate a GTK3 bug.  According to the GTK 3.18.6 docs, [gtk_scrolled_window_set_policy](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-set-policy) isn't theme conditional, and SpaceFM's code sets it [GTK_POLICY_ALWAYS](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GTK-POLICY-ALWAYS:CAPS) (the vertical scrollbar should always be visible).  You could check ~/.config/gtk-3.0/settings.ini to see if any non-default settings there affect it.

Leaving this open to collect any other info.  If anyone else sees this with Adwaita, what GTK version are you using and what distro?

**Comment by ShanaXXII** [comment]
I don't see anything out of the ordinary in my ~/.config/gtk-3.0/settings.ini
```
[Settings] 
gtk-theme-name=Adwaita
gtk-icon-theme-name=Ultra-Flat
gtk-font-name=Sans 14
gtk-cursor-theme-name=Breeze-Obsidian
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
```

**Comment by sporkbox** [comment]
Running SpaceFM 1.0.4 on GTK 3.18.6

GTK config:
~~~
[Settings] 
gtk-theme-name=MurrinaCappuccino
gtk-icon-theme-name=Faenza
gtk-font-name=Fira Sans Light 11
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-button-images=0
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=none
~~~

(Note: it looks just like Adwaita; nothing like my GTK2 theme. I can only assume my theme doesn't support GTK 3 so it uses Adwaita as a fallback)

I narrowed the columns down to just `Name` and `Size` under the View submenu. SpaceFM seems to enforce the width of the viewport to be filled. However, resizing the Size column on the right hand side expands just fine. *Narrowing it* is rather interesting. It doesn't show it getting any smaller in the headings, but its internal value *does* get smaller since after narrowing the Size column, I have to expand the Name column further to get the Size column to push out and create a horizontal scrollbar.

So, technically everything works fine. It's just a little odd. If I had to suggest a fix, it would be to find some way for the last column to update it's header's width appropriately when resizing. But then that could influence other columns. It's likely an upstream bug.

---

Steps to Reproduce:

1. Make sure you're running SpaceFM GTK3 (derp)
1. Pare down your display to just Name and Size. More is probably okay, but for the sake of testing, let's keep it simple
1. Resize the Size column on the right hand side, enlarge it. The scrollbar at the bottom should show up and/or get smaller, indicating the viewport is larger.
1. Resize the left hand side of the Size column. It functions as expected, resizing Name's width.
1. Grab the *right side* of the Size column again, this time dragging to the left to make it smaller. If there was a scrollbar, it'll narrow enough until there's no scrollbar. Drag as far left as you can. This will change the internal width of Size, but there's no visual feedback...
1. Grab the left side and start dragging to the right. Notice nothing is happening? That's because the Size column's internal width is matching the minimum width needed to display the numbers. Keep dragging right and you'll notice that when you push Size off the viewport to the right.

Sooo, *probably* an upstream thing, as I doubt SpaceFM hooks much into GTK3, but might be worth checking into.
